# Configuration for the I2Connect RAG system

# Which environment to use: "local" for all local services, "railway" for Railway-hosted services.
environment: "local"

# Folder containing source documents to index
documents_folder: "documents"

# Chunking parameters for splitting documents
chunk_size: 2000
chunk_overlap: 200

# Development flag; set to false in production
development: true

claude:
  model_name: "claude-3-5-haiku-20241022"
  max_tokens: 1000
  temperature: 0.1

# Environment-specific settings
environments:
  local:
    # Use a locally running Weaviate instance
    weaviate:
      url: "http://localhost:8080"
      index_name: "Default"
    # Use a locally running Neo4j instance
    neo4j:
      uri: "bolt://localhost:7687"
      user: "neo4j"
      password: "password"
      database: "neo4j"

  railway:
    # Use your Railway-hosted Weaviate endpoint
    weaviate:
      url: "https://weaviate-production-55d6.up.railway.app"
      index_name: "Default"
    # Use your Railway-hosted Neo4j proxy
    neo4j:
      uri: "bolt://turntable.proxy.rlwy.net:43560"
      user: "neo4j"
      password: "mg89wxdi38d1xytau4yd40d7telcxtqo"
      database: "neo4j"