# RAG System Configuration for Claude Haiku

documents_folder: "documents"
chunk_size: 500
chunk_overlap: 100
development: true

weaviate:
  url: "http://localhost:8080"
  index_name: "rag_docs"

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "neo4j"

claude:
  api_key: ""
  model_name: "claude-3-5-haiku-20241022"
  max_tokens: 1000
  temperature: 0.1

retrieval:
  default_top_k: 5
  partnership_top_k: 7
  factual_top_k: 4
  similarity_threshold: 0.3
  enable_section_reranking: true
  section_name_boost: 3.0

prompting:
  context_instructions:
    partnership: "Focus on specific organization names, roles, and contributions."
    technical: "Provide detailed technical information."
    factual: "Extract the most accurate and specific factual information."
    methodology: "Explain the methodology or approach in detail."
    general: "Synthesize the information into coherent, natural language."

chunk_processing:
  add_section_markers: true
  add_metadata_context: true
  max_context_length: 100
  section_patterns:
    - "^#{1,6}\\s+(.+)"
    - "^\\*\\*(.+)\\*\\*:?"
    - "^\\d+\\.\\s+(.+)"

logging:
  level: "INFO"
  file: "logs/rag_system.log"

hardware:
  use_gpu: false
  num_threads: 4
