chunk_overlap: 200
chunk_processing:
  add_metadata_context: true
  add_section_markers: true
  max_context_length: 100
  section_patterns:
  - ^#{1,6}\s+(.+)
  - ^\*\*(.+)\*\*:?
  - ^\d+\.\s+(.+)
chunk_size: 2000
claude:
  api_key: ''
  max_tokens: 1000
  model_name: claude-3-5-haiku-20241022
  temperature: 0.1
development: true
documents_folder: documents
embedding:
  model_name: sentence-transformers/all-MiniLM-L6-v2
hardware:
  num_threads: 4
  use_gpu: false
logging:
  file: logs/rag_system.log
  level: INFO
neo4j:
  password: password
  uri: bolt://localhost:7687
  user: neo4j
ood:
  domain_keywords:
  - evidence theory
  enabled: true
  min_neo4j_relations: 1
  similarity_check_enabled: true
  similarity_threshold: 0.25
ood_detection:
  abstention:
    confidence_explanation: true
    enable_clarification_requests: true
    enable_informed_refusal: true
    enable_partial_answers: true
  context_quality_threshold: 0.7
  enabled: true
  generation_confidence_threshold: 0.4
  graph_connectivity_threshold: 0.6
  keywords:
    tier_1_critical:
      core_concepts:
      - evidence theory
      - dempster shafer
      - uncertainty reasoning
      organizations:
      - scania
      - smart eye
      - "university of sk\xF6vde"
      - viscando
      projects:
      - i2connect
      - concept 1
      - simulation framework
    tier_2_important:
      safety_terms:
      - traffic safety
      - road safety
      - collision avoidance
      technologies:
      - driver monitoring
      - gaze tracking
      - adas
      - vehicle sensors
    tier_3_contextual:
      general_terms:
      - system
      - analysis
      - monitoring
      - detection
  quality_gates:
    max_contradiction_score: 0.3
    min_context_relevance: 0.5
    min_information_density: 0.4
    min_passage_count: 2
  response_verification:
    lexical_similarity_threshold: 0.3
    max_entropy_threshold: 2.0
    mean_entropy_threshold: 1.5
    min_relevant_passages: 2
    relevance_threshold: 0.15
    sar_threshold: 0.0
  similarity_threshold: 0.15
prompting:
  context_instructions:
    factual: Extract the most accurate and specific factual information.
    general: Synthesize the information into coherent, natural language.
    methodology: Explain the methodology or approach in detail.
    partnership: Focus on specific organization names, roles, and contributions.
    technical: Provide detailed technical information.
retrieval:
  default_top_k: 5
  enable_section_reranking: true
  factual_top_k: 4
  partnership_top_k: 7
  section_name_boost: 3.0
  similarity_threshold: 0.3
weaviate:
  index_name: rag_docs
  url: http://localhost:8080
