# RAG System Configuration for Claude Haiku

documents_folder: "documents"
chunk_size: 500
chunk_overlap: 100
development: true

weaviate:
  url: "http://localhost:8080"
  index_name: "rag_docs"

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "password"

claude:
  api_key: ""
  model_name: "claude-3-5-haiku-20241022"
  max_tokens: 1000
  temperature: 0.1

retrieval:
  default_top_k: 5
  partnership_top_k: 7
  factual_top_k: 4
  similarity_threshold: 0.3
  enable_section_reranking: true
  section_name_boost: 3.0

prompting:
  context_instructions:
    partnership: "Focus on specific organization names, roles, and contributions."
    technical: "Provide detailed technical information."
    factual: "Extract the most accurate and specific factual information."
    methodology: "Explain the methodology or approach in detail."
    general: "Synthesize the information into coherent, natural language."

chunk_processing:
  add_section_markers: true
  add_metadata_context: true
  max_context_length: 100
  section_patterns:
    - "^#{1,6}\\s+(.+)"
    - "^\\*\\*(.+)\\*\\*:?"
    - "^\\d+\\.\\s+(.+)"

logging:
  level: "INFO"
  file: "logs/rag_system.log"

hardware:
  use_gpu: false
  num_threads: 4

ood:
  enabled: true
  similarity_threshold: 0.25
  similarity_check_enabled: true
  domain_keywords:
    - evidence theory
  min_neo4j_relations: 1

ood_detection:
  enabled: true
  # Multi-layered thresholds
  similarity_threshold: 0.15
  graph_connectivity_threshold: 0.6
  context_quality_threshold: 0.7
  generation_confidence_threshold: 0.8

  # Hierarchical keyword system with weighting
  keywords:
    tier_1_critical:
      core_concepts: ["evidence theory", "dempster shafer", "uncertainty reasoning"]
      projects: ["i2connect", "concept 1", "simulation framework"]
      organizations: ["scania", "smart eye", "university of skövde", "viscando"]
    tier_2_important:
      technologies: ["driver monitoring", "gaze tracking", "adas", "vehicle sensors"]
      safety_terms: ["traffic safety", "road safety", "collision avoidance"]
    tier_3_contextual:
      general_terms: ["system", "analysis", "monitoring", "detection"]

  # Quality control parameters
  quality_gates:
    min_context_relevance: 0.7
    min_passage_count: 2
    max_contradiction_score: 0.3
    min_information_density: 0.6

  # Abstention behavior
  abstention:
    enable_informed_refusal: true
    enable_partial_answers: true
    enable_clarification_requests: true
    confidence_explanation: true

# Advanced features
response_verification:
  enable_fact_checking: true
  enable_consistency_validation: true
  enable_citation_verification: true
  hallucination_detection_threshold: 0.2
